name: rchapp_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  fl_chart: ^0.70.0
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  form_field_validator: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.1
  scrollable_table_view: ^2.0.3
  table_calendar: ^3.1.3
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/test/
    - assets/images/16/
    - assets/images/24/
    - assets/images/32/
    - assets/images/64/
    - assets/images/128/
    - assets/images/256/
    - assets/images/512/

  fonts:
    - family: Opun
      fonts:
        - asset: assets/font/Opun.ttf